platform :ios, '9.0'
inhibit_all_warnings!

target 'InvestNote_iOS' do
    
    pod 'YYKit', '1.0.9'
    pod 'AFNetworking', '3.1.0'
    pod 'MJRefresh', '3.1.15.3'
    pod 'MBProgressHUD', '1.0.0'
    pod 'SDAutoLayout', '2.2.0'
    pod 'Masonry', '1.1.0'
    pod 'IQKeyboardManager', '5.0.8'
    pod 'UMengUShare/UI', '6.4.8.2'
    pod 'UMengUShare/Social/WeChat', '6.4.8.2'
    pod 'WCDB', '1.0.6'
    pod 'AMapLocation-NO-IDFA', '2.6.0'
    pod 'Bugly'
    pod 'ReactiveObjC', '3.1.0'
    pod 'Texture', '2.7'
    
    # 'node_modules'目录一般位于根目录中
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # 如果RN版本 >= 0.47则加入此行
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 调试功能需要此模块
    'RCTAnimation', # FlatList和原生动画功能需要此模块
    'RCTImage',
    # 在这里继续添加你所需要的其他RN模块
    ]
    # 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    
    # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
end

target 'InvestNote_iOSTests' do
    
    pod 'YYKit', '1.0.9'
    pod 'AFNetworking', '3.1.0'
    pod 'MJRefresh', '3.1.15.3'
    pod 'MBProgressHUD', '1.0.0'
    pod 'SDAutoLayout', '2.2.0'
    pod 'Masonry', '1.1.0'
    pod 'IQKeyboardManager', '5.0.8'
    pod 'UMengUShare/UI', '6.4.8.2'
    pod 'UMengUShare/Social/WeChat', '6.4.8.2'
    pod 'WCDB', '1.0.6'
    pod 'AMapLocation-NO-IDFA', '2.6.0'
    pod 'Bugly'
    pod 'ReactiveObjC', '3.1.0'
    pod 'Texture', '2.7'
    
    # 'node_modules'目录一般位于根目录中
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # 如果RN版本 >= 0.47则加入此行
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 调试功能需要此模块
    'RCTAnimation', # FlatList和原生动画功能需要此模块
    'RCTImage',
    # 在这里继续添加你所需要的其他RN模块
    ]
    # 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    
    # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

